# Generated by Django 4.0.6 on 2022-07-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200, unique=True)),
                ('room_password', models.CharField(max_length=100)),
                ('total_player', models.IntegerField()),
                ('bhabi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bhabi', to='sylApp.player')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='sylApp.player')),
                ('player', models.ManyToManyField(to='sylApp.player')),
            ],
        ),
    ]
