# Generated by Django 4.0.6 on 2022-07-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sylApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_player',
        ),
        migrations.AlterField(
            model_name='room',
            name='bhabi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bhabi', to='sylApp.player'),
        ),
    ]
